jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
# Make
  - task: CMake@1
    inputs:
      workingDirectory: .\build
      cmakeArgs: ..\
    displayName: CMake project

  - task: MSBuild@1
    inputs: 
      solution: .\build\cpp_babaisyou.sln
    displayName: MSBuild project
  
  - task: MSBuild@1
    inputs:
      solution: .\build\unittest\unittest.sln
    displayName: MSBuild unittest
# UnitTest
  - script: .\build\unittest\Debug\unittest.exe
    displayName: Start unittest
